modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL="https://github.com/JamCoreModding/sort-it-out/issues"

[[mods]]
modId = "sort_it_out"
version = "${version}"
displayName = "Sort It Out!"
displayURL="https://github.com/JamCoreModding/sort-it-out"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
A capable inventory sorting mod that works either client-side or server-side
'''

[[dependencies.sort_it_out]]
modId = "forge"
mandatory = true
versionRange = "[47.4.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sort_it_out]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sort_it_out]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sort_it_out]]
modId = "jamlib"
mandatory = true
versionRange = "[${jamlib_version},)"
ordering = "AFTER"
side = "BOTH"
