plugins {
    id "com.github.johnrengelman.shadow" version "8.1.1"
    id "me.modmuss50.mod-publish-plugin"
}

architectury {
    platformSetupLoomIde()
    fabric()
}

base {
    archivesName = "sort_it_out-fabric"
}

configurations {
    common
    shadowCommon 
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    modImplementation libs.fabric.loader
    modImplementation libs.fabric.api
    modImplementation libs.architectury.fabric
    modRuntimeOnly libs.modmenu
    modImplementation libs.jamlib.fabric

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }
}

if (System.getenv("CURSEFORGE_API_KEY") != null && System.getenv("MODRINTH_API_KEY") != null) {
    publishMods {
        file = tasks.remapJar.archiveFile
        displayName = "V${project.version} (Fabric ${project.minecraft_version})"
        changelog = rootProject.file("CHANGELOG.md").text
        type = project.version.contains("beta") ? BETA : STABLE
        modLoaders.add("fabric")

        curseforge {
            projectId = "1215281"
            accessToken = providers.environmentVariable("CURSEFORGE_API_KEY")
            client = true
            server = true
            minecraftVersions.add(project.minecraft_version)
            minecraftVersions.addAll(project.additional_minecraft_versions == "" ? [] : project.additional_minecraft_versions.split(","))
            requires("fabric-api")
            requires("jamlib")
        }

        modrinth {
            projectId = "jcOSOvm1"
            accessToken = providers.environmentVariable("MODRINTH_API_KEY")
            minecraftVersions.add(project.minecraft_version)
            minecraftVersions.addAll(project.additional_minecraft_versions == "" ? [] : project.additional_minecraft_versions.split(","))
            requires("fabric-api")
            requires("jamlib")
        }
    }
}

processResources {  
	def substitutions = [
	        "version"             : project.version,
	        "minecraft_version"   : project.minimum_minecraft_version,
	        "fabric_api_version"  : project.minimum_fabric_api_version,
	        "architectury_version": project.minimum_architectury_api_version,
	        "jamlib_version"      : project.minimum_jamlib_version
	]

    filesMatching("fabric.mod.json") {
        expand substitutions
    }

    substitutions.each { inputs.property it.key, it.value }
}

shadowJar {
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    injectAccessWidener = true
    input.set shadowJar.archiveFile
    dependsOn shadowJar
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}
