modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL="https://github.com/JamCoreModding/sort-it-out/issues"

[[mods]]
modId = "sort_it_out"
version = "${version}"
displayName = "Sort It Out!"
displayURL="https://github.com/JamCoreModding/sort-it-out"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
A capable inventory sorting mod that works either client-side or server-side
'''

[[dependencies.sort_it_out]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sort_it_out]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sort_it_out]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sort_it_out]]
modId = "jamlib"
type = "required"
versionRange = "[${jamlib_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "sort_it_out.mixins.json"

[[mixins]]
config = "sort_it_out.client.mixins.json"
