plugins {
    id "com.github.johnrengelman.shadow" version "8.1.1"
    id "me.modmuss50.mod-publish-plugin"
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

base {
    archivesName = "sort_it_out-neoforge"
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

repositories {
    maven {
        name = "NeoForge"
        url = "https://maven.neoforged.net/releases"
    }
}

dependencies {
    neoForge libs.neoforge
    modImplementation libs.architectury.neoforge
    modImplementation libs.jamlib.neoforge

    // Dependency of JamLib
    forgeRuntimeLibrary "blue.endless:jankson:1.2.3"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionNeoForge")) { transitive = false }
}

if (System.getenv("CURSEFORGE_API_KEY") != null && System.getenv("MODRINTH_API_KEY") != null) {
     publishMods {
        file = tasks.remapJar.archiveFile
        displayName = "V${project.version} (NeoForge ${project.minecraft_version})"
        changelog = rootProject.file("CHANGELOG.md").text
        type = project.version.contains("beta") ? BETA : STABLE
        modLoaders.add("neoforge")

        curseforge {
            projectId = "1215281"
            accessToken = providers.environmentVariable("CURSEFORGE_API_KEY")
            client = true
            server = true
            minecraftVersions.add(project.minecraft_version)
            minecraftVersions.addAll(project.additional_minecraft_versions == "" ? [] : project.additional_minecraft_versions.split(","))
            requires("jamlib")
        }

        modrinth {
            projectId = "jcOSOvm1"
            accessToken = providers.environmentVariable("MODRINTH_API_KEY")
            minecraftVersions.add(project.minecraft_version)
            minecraftVersions.addAll(project.additional_minecraft_versions == "" ? [] : project.additional_minecraft_versions.split(","))
            requires("jamlib")
        }
    }
}

processResources {  
    def substitutions = [  
            "version"             : project.version,
            "minecraft_version"   : project.minimum_minecraft_version,
            "neoforge_version"    : project.minimum_minecraft_version.substring(2),
            "architectury_version": project.minimum_architectury_api_version,
            "jamlib_version"      : project.minimum_jamlib_version
    ]

    filesMatching("META-INF/neoforge.mods.toml") {
        expand substitutions
    }

    substitutions.each { inputs.property it.key, it.value } 
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}
